name: base
channels:
  - pytorch
  - photosynthesis-team
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asciitree=0.3.3=py_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boltons=23.0.0=py311haa95532_0
  - bottleneck=1.3.5=py311h5bb9823_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2024.3.11=haa95532_0
  - catalogue=2.0.10=py311h1ea47a8_0
  - certifi=2024.6.2=py311haa95532_0
  - cffi=1.16.0=py311h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpathlib=0.16.0=pyhd8ed1ab_0
  - cloudpickle=2.2.1=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - conda=24.5.0=py311haa95532_0
  - conda-content-trust=0.2.0=py311haa95532_0
  - conda-libmamba-solver=23.12.0=pyhd3eb1b0_1
  - conda-package-handling=2.2.0=py311haa95532_0
  - conda-package-streaming=0.9.0=py311haa95532_0
  - confection=0.1.4=py311h3810d55_0
  - console_shortcut_miniconda=0.1.1=haa95532_1
  - contourpy=1.2.0=py311h005e61a_0
  - cryptography=41.0.7=py311h89fc84f_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-opencl-dev=12.3.101=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=12.1.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py311hd77b12b_0
  - distro=1.8.0=py311haa95532_0
  - docker-pycreds=0.4.0=py_0
  - efficientnet-pytorch=0.7.1=pyhd8ed1ab_1
  - executing=0.8.3=pyhd3eb1b0_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - filelock=3.13.1=py311haa95532_0
  - fmt=9.1.0=h6d14046_0
  - fonttools=4.47.0=py311ha68e1ae_0
  - freetype=2.12.1=ha860e81_0
  - frozendict=2.4.2=py311haa95532_0
  - fsspec=2023.12.2=pyhca7485f_0
  - gettext=0.21.1=h5728263_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glib=2.78.3=h12be248_0
  - glib-tools=2.78.3=h12be248_0
  - gmpy2=2.1.2=py311h7f96b67_0
  - gst-plugins-base=1.22.8=h001b923_0
  - gstreamer=1.22.8=hb4038d2_0
  - gudhi=3.9.0=py311hda12aea_5
  - huggingface_hub=0.20.0=pyhd8ed1ab_0
  - icu=70.1=h0e60522_0
  - idna=3.4=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.25.0=py311h746a85d_0
  - ipython=8.15.0=py311haa95532_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py311haa95532_1
  - jinja2=3.1.2=py311haa95532_0
  - joblib=1.2.0=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.0=py311haa95532_0
  - jupyter_core=5.5.0=py311haa95532_0
  - kiwisolver=1.4.5=py311h005e61a_1
  - krb5=1.20.1=heb0366b_0
  - lerc=2.2.1=h0e60522_0
  - libarchive=3.6.2=hb62f4d4_2
  - libblas=3.9.0=1_h8933c1f_netlib
  - libboost=1.82.0=h65993cd_6
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=15.0.7=default_h77d9078_3
  - libclang13=15.0.7=default_h77d9078_3
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcurl=8.4.0=h86230a5_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.7=h8ffe710_5
  - libffi=3.4.4=hd77b12b_0
  - libglib=2.78.3=h16e383f_0
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libmamba=1.5.3=hcd6fe79_0
  - libmambapy=1.5.3=py311h77c03ed_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libprotobuf=3.21.12=h12be248_2
  - libsodium=1.0.18=h62dcd97_0
  - libsolv=0.7.24=h23ce68f_0
  - libsqlite=3.44.2=hcfcfb64_0
  - libssh2=1.10.0=he2ea4bf_2
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.3.2=hcfcfb64_1
  - libwebp-base=1.3.2=hcfcfb64_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib=3.8.2=py311h1ea47a8_0
  - matplotlib-base=3.8.2=py311h6e989c2_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - menuinst=2.0.1=py311hd77b12b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.8=py311h2bbff1b_0
  - mkl_random=1.2.4=py311h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.2.1=h64bf75a_0
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py311haa95532_0
  - msgpack-python=1.0.7=py311h005e61a_0
  - msys2-conda-epoch=20160418=1
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.5.6=py311haa95532_0
  - networkx=3.1=py311haa95532_0
  - nltk=3.8.1=py311haa95532_0
  - numcodecs=0.12.1=py311h12c1d0e_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.24.3=py311hdab7c0b_1
  - numpy-base=1.24.3=py311hd01c5d8_1
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.2.0=hcfcfb64_1
  - packaging=23.1=py311haa95532_0
  - pandas=2.1.1=py311hf62ec03_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=py_1
  - pcre2=10.42=h0ff8eda_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py311h045eedc_0
  - pip=23.3.1=py311haa95532_0
  - piq=0.8.0=py_0
  - platformdirs=3.10.0=py311haa95532_0
  - pluggy=1.0.0=py311haa95532_1
  - ply=3.11=py_1
  - powershell_shortcut_miniconda=0.0.1=haa95532_1
  - pretrainedmodels=0.7.4=pyhd8ed1ab_2
  - prompt-toolkit=3.0.36=py311haa95532_0
  - protobuf=4.21.12=py311h12c1d0e_0
  - psutil=5.9.7=py311ha68e1ae_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py311h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic-core=2.14.6=py311hc37eb10_1
  - pygments=2.15.1=py311haa95532_1
  - pyopenssl=23.2.0=py311haa95532_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.10=py311hd77b12b_0
  - pyqt5-sip=12.13.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.1.2=py3.11_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.0=py311hd77b12b_0
  - qt-main=5.15.8=h720456b_6
  - regex=2023.10.3=py311h2bbff1b_0
  - reproc=14.2.4=hd77b12b_1
  - reproc-cpp=14.2.4=hd77b12b_1
  - requests=2.31.0=py311haa95532_0
  - rich=13.7.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py311h2bbff1b_0
  - safetensors=0.3.3=py311hc37eb10_1
  - scikit-learn=1.3.0=py311hf62ec03_0
  - scipy=1.11.4=py311h0b4df5a_0
  - segmentation-models-pytorch=0.3.3=pyhd8ed1ab_0
  - sentry-sdk=1.39.1=pyhd8ed1ab_0
  - setproctitle=1.3.3=py311ha68e1ae_0
  - setuptools=68.2.2=py311haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - sip=6.7.12=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=6.4.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - spyder-kernels=2.5.0=win_pyh7428d3b_0
  - sqlite=3.41.2=h2bbff1b_0
  - srsly=2.4.8=py311h12c1d0e_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - timm=0.9.2=pyhd8ed1ab_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.3=py311ha68e1ae_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py311haa95532_0
  - truststore=0.8.0=py311haa95532_0
  - typing-extensions=4.7.1=py311haa95532_0
  - typing_extensions=4.7.1=py311haa95532_0
  - tzdata=2023c=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.18=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - weasel=0.3.4=pyhd8ed1ab_0
  - wheel=0.41.2=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_0
  - zarr=2.16.1=pyhd8ed1ab_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstandard=0.19.0=py311h2bbff1b_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.1.0
      - ale-py==0.8.1
      - alpaca==1.0.0
      - blis==0.7.11
      - box2d-py==2.3.5
      - comm==0.2.1
      - cymem==2.0.8
      - cython==0.29.37
      - decorator==4.4.2
      - emoji==2.9.0
      - en-core-web-sm==3.7.1
      - es-core-news-sm==3.7.0
      - etils==1.9.1
      - farama-notifications==0.0.4
      - glfw==2.7.0
      - gymnasium==0.29.1
      - imageio==2.34.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==3.10.1
      - importlib-resources==6.4.0
      - ipywidgets==8.1.2
      - jax==0.4.28
      - jaxlib==0.4.28
      - jupyterlab-widgets==3.0.10
      - langcodes==3.3.0
      - lz4==4.3.3
      - ml-dtypes==0.4.0
      - moviepy==1.0.3
      - mujoco==3.1.6
      - mujoco-py==2.1.2.14
      - murmurhash==1.0.10
      - opencv-contrib-python==4.8.1.78
      - opencv-python==4.10.0.82
      - opt-einsum==3.3.0
      - pathy==0.10.3
      - pcfg==0.1.5
      - preshed==3.0.9
      - proglog==0.1.10
      - pydantic==1.8.2
      - pygame==2.5.2
      - pyopengl==3.1.7
      - shimmy==0.2.1
      - spacy-conll==3.4.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-stanza==1.0.3
      - stanza==1.5.0
      - swig==4.2.1
      - thinc==8.1.12
      - tokenizers==0.13.3
      - toml==0.10.2
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - transformers==4.32.1
      - typer==0.4.2
      - wandb==0.17.2
      - wasabi==0.10.1
      - widgetsnbextension==4.0.10
prefix: C:\Users\Mateo-drr\AppData\Local\miniconda3
